#!/usr/bin/env bash
# =============================================================================
# restrict-ssh.sh — SSH access cutover: two identity-gated paths (Phase 0.2/0.3)
#
# Restricts inbound tcp/22 to:
#   (1) loopback        — cloudflared tunnel egress for the SSH-over-
#                         Cloudflare-Access path (Access app at the CF edge,
#                         tunnel ingress ssh://localhost:22)
#   (2) tailscale0      — Tailscale SSH / tailnet sshd
# Every other source is rate-limited logged ("ssh-guard-drop: ") and dropped.
# sshd itself stays on port 22 on all interfaces; this firewall rule is the
# access boundary. IPv4 and IPv6 both covered (inet family).
#
# DECISION (founder, 2026-09-26): admin SSH has exactly two identity-gated
# paths — Cloudflare Access SSH and Tailscale SSH. Direct SSH by public IP is
# denied. Recorded in ARCHITECTURE §6/§18 and the CONTEXT_HYBRID change log.
#
# ACCEPTED INTERIM RISKS:
#  - The SSH-over-tunnel path authenticates at the Cloudflare Access edge
#    (Access app policy: named users, MFA/passkey, short session). The origin
#    does not validate Cf-Access-Jwt-Assertion for TCP/SSH; HTTP-surface JWT
#    validation is the Phase 5 gate.
#  - If UFW (scripts/hardenning.sh) is still active, its "allow 22/tcp" rule is
#    superseded by this guard chain (a drop in any base chain is final), but
#    two firewall managers must not persist: after confirming, follow
#    scripts/README.md Step 3 to migrate to the reviewed nftables policy and
#    then `ufw disable` — only after `systemctl enable nftables` + a reboot test.
#  - Loopback is trusted for the tunnel path; off-box traffic cannot source
#    loopback, so no further uid/ip narrowing on lo.
#
# BREAK-GLASS: unaffected. OVH KVM console and rescue mode boot an independent
# environment; neither consults this host's firewall configuration.
#
# WARNING: applying this terminates existing direct-IP SSH sessions. Keep a
# Cloudflare Access (or Tailscale) session open and run this script FROM it.
#
# SAFETY (same pattern as setup-nftables.sh, spec §6.1.1): every apply
# schedules an `at now + 5 minutes` job restoring the pre-apply ruleset.
# Confirm within the deadline or the change rolls back automatically.
# Shares the rollback slot with setup-nftables.sh (one failsafe at a time).
#
# Usage:
#   sudo ./restrict-ssh.sh apply      # snapshot + at-rollback + apply
#   sudo ./restrict-ssh.sh confirm    # tested OK -> remove rollback job
#   sudo ./restrict-ssh.sh rollback   # manual restore of known-good now
#   sudo ./restrict-ssh.sh status     # show guard rules + recent drops
# =============================================================================
set -euo pipefail

CONF="/etc/nftables.conf"
BACKUP_DIR="/var/backups/nftables"
GOOD="${BACKUP_DIR}/known-good.nft"
JOBFILE="${BACKUP_DIR}/rollback-job"
TABLE="ssh_guard"
TAILSCALE_IF="${TAILSCALE_IF:-tailscale0}"
LOG_PREFIX="ssh-guard-drop: "
ROLLBACK_MODE=nft

log() { printf '[restrict-ssh] %s\n' "$*"; }
die() { printf '[restrict-ssh] ERROR: %s\n' "$*" >&2; exit 1; }

require_root() {
  [[ $EUID -eq 0 ]] || die "run as root (sudo)"
  command -v nft >/dev/null || die "nftables not installed"
  command -v at >/dev/null || die "'at' not installed (apt install at)"
  systemctl is-active --quiet atd || die "atd not running"
}

render_guard() {
  cat <<EOF
#!/usr/sbin/nft -f
# Generated by restrict-ssh.sh — SSH access guard (two identity-gated paths)
table inet ${TABLE} {
    chain input {
        type filter hook input priority 0; policy accept;
        # Path 1: cloudflared -> ssh://localhost:22 arrives on loopback
        iifname "lo" tcp dport 22 accept
        # Path 2: Tailscale SSH / tailnet sshd arrives on ${TAILSCALE_IF}
        iifname "${TAILSCALE_IF}" tcp dport 22 accept
        # Everything else to 22: log (rate-limited) and drop
        tcp dport 22 limit rate 5/second counter log prefix "${LOG_PREFIX}"
        tcp dport 22 counter drop
    }
}
EOF
}

snapshot_known_good() {
  # CRITICAL (panel finding, same as setup-nftables.sh): 'nft list ruleset'
  # output alone would MERGE into the live table on reload. The snapshot must
  # start with 'flush ruleset' to actually REPLACE.
  { echo "#!/usr/sbin/nft -f"; echo "flush ruleset"; nft list ruleset; } > "${GOOD}"
  chmod 600 "${GOOD}"
  # REAL-TEST FINDING (sandbox battery 2026-09-26): with UFW active the dump
  # contains iptables-nft 'xt' compat expressions that 'nft -f' REJECTS —
  # a bare 'nft -f' rollback fires but restores nothing. Validate the
  # snapshot; if it is not nft-loadable, the rollback path falls back to
  # 'flush ruleset' + UFW restart (see rollback.sh / do_rollback).
  if nft -c -f "${GOOD}" >/dev/null 2>&1; then
    ROLLBACK_MODE=nft
  else
    ROLLBACK_MODE=compat
    log "WARNING: known-good snapshot contains iptables-nft compat expressions (UFW active). Rollback will use the resilient path (flush + UFW restart)."
  fi
}

write_rollback_script() {
  # Resilient restore used by BOTH the at job and manual rollback:
  # 1. try the pure-nft snapshot; if nft rejects it (UFW/iptables-nft tables),
  # 2. flush everything (kernel default = ACCEPT, always 'get back in'), then
  # 3. restart UFW so its own rules are rebuilt — pre-apply state restored.
  cat > "${BACKUP_DIR}/rollback.sh" <<EOF
#!/usr/bin/env bash
set -u
if ! nft -f '${GOOD}' 2>/dev/null; then
  nft flush ruleset 2>/dev/null || true
  systemctl restart ufw 2>/dev/null || ufw reload 2>/dev/null || true
fi
EOF
  chmod 700 "${BACKUP_DIR}/rollback.sh"
}

schedule_rollback() {
  # Remove any stale unconfirmed job first (an old job could later restore an
  # outdated baseline over a confirmed state — panel finding).
  local oldjob
  oldjob=$(cat "${JOBFILE}" 2>/dev/null || true)
  [[ -n "${oldjob}" ]] && atrm "${oldjob}" 2>/dev/null || true
  # REAL-TEST FINDING (sandbox battery 2026-09-26): at 3.2.x prints its
  # 'job N at ...' confirmation to STDERR, so 'at | awk' captured nothing and
  # apply aborted. Schedule, then read the id from atq (highest id = ours).
  write_rollback_script
  echo "${BACKUP_DIR}/rollback.sh" | at now + 5 minutes >/dev/null 2>&1 || true
  atq | awk '{print $1}' | sort -n | tail -1 > "${JOBFILE}" || true
  chmod 600 "${JOBFILE}" 2>/dev/null || true
}

do_apply() {
  require_root

  # Warn (do not fail) if UFW is active — its allow-22 rule is superseded by
  # this guard chain, but the UFW layer must be retired after migration.
  if command -v ufw >/dev/null 2>&1 && ufw status 2>/dev/null | grep -q '^Status: active'; then
    log "WARNING: UFW is active. Its 'allow 22/tcp' is superseded by this guard chain (a drop in any base chain is final), but retire UFW after the Phase 0.3 nftables migration (scripts/README.md Step 3)."
  fi

  mkdir -p "${BACKUP_DIR}"

  # 1. Snapshot the CURRENT live ruleset as known-good. A reused snapshot is
  #    only trustworthy if it equals the live state (real-test finding
  #    F-T3, round 3, 2026-09-26): an UNCONFIRMED prior apply leaves a stale
  #    pre-apply snapshot on disk; rolling back to it would WIPE the live
  #    policy. Validate before reuse; otherwise re-snapshot live state.
  local snap_ok=1
  if [[ -s "${GOOD}" ]] && nft -c -f "${GOOD}" >/dev/null 2>&1 \
     && [[ "$(tail -n +3 "${GOOD}")" == "$(nft list ruleset)" ]]; then
    snap_ok=1
  else
    snap_ok=0
  fi
  if (( ! snap_ok )); then
    snapshot_known_good
  fi

  # 2. Schedule the timed rollback job (THE safety net). Shares the rollback
  #    slot with setup-nftables.sh — one failsafe at a time.
  schedule_rollback
  local job
  job=$(cat "${JOBFILE}" 2>/dev/null || true)
  [[ -n "${job}" ]] || die "could not schedule the rollback 'at' job — aborting"

  # Verify the job is registered (real-test finding: capture can silently
  # pick the wrong id if jobs race) — the id must exist in atq.
  atq | awk '{print $1}' | grep -qx "${job}" \
    || die "rollback 'at' job ${job} not found in atq — aborting"

  # 3. Render + validate the guard ruleset. NOTE: this does NOT replace
  #    /etc/nftables.conf — setup-nftables.sh remains the full-policy path;
  #    the guard table coexists with UFW/fail2ban chains (no 'flush ruleset').
  render_guard > "${CONF}.guard"
  chmod 700 "${CONF}.guard"
  if ! nft -c -f "${CONF}.guard"; then
    rm -f "${CONF}.guard"
    die "guard validation failed; nothing applied"
  fi

  # 4. Idempotency: drop a previous guard table before re-applying.
  if nft list table "inet ${TABLE}" >/dev/null 2>&1; then
    nft delete table "inet ${TABLE}"
  fi
  nft -f "${CONF}.guard" || die "apply failed — run: sudo $0 rollback"
  rm -f "${CONF}.guard"

  log "applied. tcp/22 now accepted ONLY via loopback (CF Access tunnel) and ${TAILSCALE_IF}."
  log "Direct-IP SSH sessions were terminated; new ones are logged + dropped."
  log "ROLLBACK job id=${job} fires in 5 minutes."
  log "tested everything OK?  -> sudo $0 confirm"
  log "something broken?      -> wait 5 min (auto-rollback) or: sudo $0 rollback"
}

do_confirm() {
  require_root
  local job
  job=$(cat "${JOBFILE}" 2>/dev/null || true)
  if [[ -n "${job}" ]]; then
    atrm "${job}" 2>/dev/null || true
  fi
  snapshot_known_good
  write_rollback_script
  rm -f "${JOBFILE}"
  log "confirmed. SSH guard is now the baseline (known-good snapshot updated)."
}

do_rollback() {
  require_root
  [[ -s "${GOOD}" ]] || die "no known-good snapshot at ${GOOD}"
  local job
  job=$(cat "${JOBFILE}" 2>/dev/null || true)
  if [[ -n "${job}" ]]; then
    atrm "${job}" 2>/dev/null || true
  fi
  # Resilient path (real-test finding): nft-only restore fails on
  # UFW/iptables-nft compat tables; fallback flushes + restarts UFW.
  write_rollback_script
  if "${BACKUP_DIR}/rollback.sh"; then
    log "rolled back to known-good."
  else
    die "rollback failed — restore manually via OVH KVM console: nft -f ${GOOD}"
  fi
}

do_status() {
  require_root
  if nft list table "inet ${TABLE}" >/dev/null 2>&1; then
    nft list table "inet ${TABLE}"
  else
    log "no ${TABLE} table present"
  fi
  journalctl -k --since "-30 min" 2>/dev/null | grep "ssh-guard-drop" | tail -n 10 || true
}


case "${1:-}" in
  apply)    do_apply ;;
  confirm)  do_confirm ;;
  rollback) do_rollback ;;
  status)   do_status ;;
  *) die "usage: $0 {apply|confirm|rollback|status}" ;;
esac
