#!/usr/bin/env bash
# =============================================================================
# setup-nftables.sh — Phase 0.3 (PLAN.md)
#
# Applies the base firewall:
#   INPUT/FORWARD/OUTPUT = default DROP
#   INPUT: allow loopback, established, ICMP(6) rate-limited, Tailscale UDP,
#          SSH ONLY from the tailscale0 interface
#   OUTPUT: allow established, loopback, pinned DNS resolvers, NTP, HTTPS/HTTP
#           (interim; see DECISION below), Tailscale transports; explicit DROP
#           of egress to private/link-local/metadata ranges on the WAN side;
#           log-and-drop the rest (rate-limited).
#
# SAFETY (v0.3 spec §6.1.1): every apply schedules an `at now + 5 minutes`
# job that restores the previous known-good ruleset. Confirm within the
# deadline or the change rolls back automatically. No lockouts from bad rules.
# CAVEAT (panel finding): the at job does not survive a reboot inside the
# 5-minute window — if the box reboots before you confirm, use the OVH
# console/KVM (break-glass, spec §13) or re-run this script.
#
# DECISION (documented interim): TCP 443/80 is allowed to any destination in
# Phase 0. Nearly all infra egress (packages, cloudflared, R2, Infisical,
# model APIs) is HTTPS, and domain-level allowlisting requires the egress
# proxy that arrives in Phase 3. DNS is pinned to approved resolvers and
# private/metadata ranges are hard-blocked. The Phase 3 proxy narrows this.
#
# ACCEPTED RISKS until Phase 3 (expert-panel review 2026-09-24):
#  - DoH/DoT to a hardcoded IP on 443 bypasses the DNS pin entirely — the
#    pin is NOT an exfil control for a compromised process, it only stops
#    casual port-53 use. Phase 3's proxy must force resolution.
#  - DNS tunneling THROUGH the pinned recursive resolvers is still possible
#    (recursive resolver forwards attacker-domain queries). Content-level
#    DNS control arrives with the Phase 3 proxy.
#  - Hairpin to the box's own WAN IP over 443 is reachable (443-any).
#
# Usage:
#   sudo ./setup-nftables.sh apply      # snapshot + at-rollback + apply
#   sudo ./setup-nftables.sh confirm    # tested OK -> remove rollback job
#   sudo ./setup-nftables.sh rollback   # manual restore of known-good now
# =============================================================================
set -euo pipefail

CONF="/etc/nftables.conf"
BACKUP_DIR="/var/backups/nftables"
GOOD="${BACKUP_DIR}/known-good.nft"
JOBFILE="${BACKUP_DIR}/rollback-job"
TAILSCALE_IF="${TAILSCALE_IF:-tailscale0}"
# DNS resolvers we pin outbound DNS to (Cloudflare, Google; adjust to taste)
RESOLVERS="${RESOLVERS:-1.1.1.1 1.0.0.1 8.8.8.8}"

log() { printf '[setup-nftables] %s\n' "$*"; }
die() { printf '[setup-nftables] ERROR: %s\n' "$*" >&2; exit 1; }

require_root() {
  [[ $EUID -eq 0 ]] || die "run as root (sudo)"
  command -v nft >/dev/null || die "nftables not installed"
  command -v at >/dev/null || die "'at' not installed (apt install at)"
  systemctl is-active --quiet atd || die "atd not running"
}

wan_iface() {
  ip -4 route show default | awk '{print $5; exit}'
}

render_ruleset() {
  local wan="$1"
  # Build a resolver set line: "1.1.1.1, 1.0.0.1, 8.8.8.8"
  local res
  res=$(echo "$RESOLVERS" | tr ' ' '\n' | sed 's/^/        /; s/$/,/' | sed '$s/,$//')
  cat <<EOF
#!/usr/sbin/nft -f
# Generated by setup-nftables.sh — Phase 0.3 base policy
flush ruleset

table inet filter {
    set dns_resolvers {
        type ipv4_addr
        elements = {
${res}
        }
    }

    chain input {
        type filter hook input priority 0; policy drop;
        iifname "lo" accept
        ct state established,related accept
        # Rate-limited ICMP/ICMPv6 (keep diagnostics, stop floods)
        ip protocol icmp icmp type echo-request limit rate 5/second accept
        meta l4proto ipv6-icmp icmpv6 type { nd-neighbor-solicit, nd-neighbor-advert } accept
        meta l4proto ipv6-icmp icmpv6 type { destination-unreachable, packet-too-big, time-exceeded, parameter-problem, echo-request, 135, 136 } limit rate 5/second accept
        # Tailscale transports may arrive on the WAN iface
        udp port 41641 accept
        # SSH ONLY via the tailnet
        iifname "${TAILSCALE_IF}" tcp port 22 accept
        # Everything else: log (rate-limited) and drop
        limit rate 5/second counter log prefix "nft-in-drop: "
        counter drop
    }

    chain forward {
        type filter hook forward priority 0; policy drop;
        counter drop
    }

    chain output {
        type filter hook output priority 0; policy drop;
        oifname "lo" accept
        ct state established,related accept
        # --- Trusted tailnet path FIRST: Tailscale uses 100.64/10 (CGNAT)
        # addressing, so this accept MUST precede the CGNAT drop below.
        oifname "${TAILSCALE_IF}" accept
        # --- SSRF/private-range hard blocks BEFORE the service accepts ---
        # nft is first-match: if these sit below the 80/443/123 accepts, the
        # metadata endpoint and RFC1918 stay reachable via allowed ports
        # (expert-panel finding; spec section 9).
        ip daddr { [IP_ADDRESS]/8, [IP_ADDRESS]/12, [IP_ADDRESS]/16, [IP_ADDRESS]/16, [IP_ADDRESS]/8, [IP_ADDRESS]/8, [IP_ADDRESS]/10, [IP_ADDRESS]/4, [IP_ADDRESS]/4 } counter drop
        ip6 daddr { fc00::/7, fe80::/10, ::1 } counter drop
        # --- Infrastructure egress (allowlist) ---
        # DNS pinned to approved resolvers only (no open port-53 exfil)
        ip daddr @dns_resolvers udp port 53 accept
        ip daddr @dns_resolvers tcp port 53 accept
        # NTP pinned to time.cloudflare.com (panel finding: unpinned udp/123
        # is an open beacon channel)
        ip daddr { [IP_ADDRESS], [IP_ADDRESS] } udp port 123 accept
        # HTTPS/HTTP: interim allowlist (packages, cloudflared, R2, Infisical,
        # model APIs). Narrowed to domain-level policy by the Phase 3 proxy.
        tcp port { 80, 443 } accept
        # Tailscale direct traffic. STUN (3478) intentionally DROPPED:
        # DERP-over-443 fallback keeps Tailscale functional (relay mode) and
        # closes an unpinned beacon channel (panel finding).
        udp port 41641 accept
        # --- Log and drop the rest ---
        limit rate 10/second counter log prefix "nft-out-drop: "
        counter drop
    }
}
EOF
}

do_apply() {
  require_root
  local wan
  wan=$(wan_iface) || die "no default route / WAN interface found"
  mkdir -p "${BACKUP_DIR}"

  # 1. Snapshot the CURRENT live ruleset as known-good (or keep existing one
  #    if this is not the first apply, so rollback returns to the last
  #    confirmed state).
  if [[ ! -s "${GOOD}" ]]; then
    # CRITICAL (panel finding): 'nft list ruleset' output alone would MERGE
    # into the live table on reload (append after the terminal drop rule).
    # The snapshot must start with 'flush ruleset' to actually REPLACE.
    { echo "#!/usr/sbin/nft -f"; echo "flush ruleset"; nft list ruleset; } > "${GOOD}"
    chmod 600 "${GOOD}"
  fi

  # 2. Schedule the timed rollback job (THE safety net).
  # Remove any stale unconfirmed job first (panel finding: an old job could
  # later restore an outdated baseline over a confirmed state).
  local oldjob
  oldjob=$(cat "${JOBFILE}" 2>/dev/null || true)
  [[ -n "${oldjob}" ]] && atrm "${oldjob}" 2>/dev/null
  echo "nft -f ${GOOD}" | at now + 5 minutes 2>/dev/null \
    | awk '/job/ {print $2}' > "${JOBFILE}" || true
  chmod 600 "${JOBFILE}" 2>/dev/null || true
  local job
  job=$(cat "${JOBFILE}" 2>/dev/null || true)
  [[ -n "${job}" ]] || die "could not schedule the rollback 'at' job — aborting"

  # 3. Render + apply the new ruleset.
  render_ruleset "${wan}" > "${CONF}.new"
  chmod 700 "${CONF}.new"
  nft -c -f "${CONF}.new" || die "ruleset validation failed; nothing applied"
  mv "${CONF}.new" "${CONF}"
  nft -f "${CONF}" || die "apply failed — run: sudo $0 rollback"

  log "applied. ROLLBACK job id=${job} fires in 5 minutes."
  log "tested everything OK?  -> sudo $0 confirm"
  log "something broken?      -> wait 5 min (auto-rollback) or: sudo $0 rollback"
}

do_confirm() {
  require_root
  local job
  job=$(cat "${JOBFILE}" 2>/dev/null || true)
  if [[ -n "${job}" ]]; then
    atrm "${job}" 2>/dev/null || true
  fi
  { echo "#!/usr/sbin/nft -f"; echo "flush ruleset"; nft list ruleset; } > "${GOOD}"
  chmod 600 "${GOOD}"
  rm -f "${JOBFILE}"
  log "confirmed. New ruleset is now the known-good baseline."
}

do_rollback() {
  require_root
  [[ -s "${GOOD}" ]] || die "no known-good snapshot at ${GOOD}"
  local job
  job=$(cat "${JOBFILE}" 2>/dev/null || true)
  if [[ -n "${job}" ]]; then
    atrm "${job}" 2>/dev/null || true
  fi
  nft -f "${GOOD}" && log "rolled back to known-good."
}

case "${1:-}" in
  apply)    do_apply ;;
  confirm)  do_confirm ;;
  rollback) do_rollback ;;
  *) die "usage: $0 {apply|confirm|rollback}" ;;
esac
